### ISSUE TITLE
界面配色适配主题

### ISSUE THREAD

**Issue by chenshinshi** [caohongliang92/siyuan-plugin-more-cover#1]
作者您好，请问可否将现在的界面配色改为变量，如背景色取--b3-theme-surface，可以参考设置界面或者其他dialog的取色，这样可以适配更多主题尤其是夜间主题。
![image](https://github.com/caohongliang92/siyuan-plugin-more-cover/assets/125173405/56342fb0-454d-4d21-8289-714b6873e3c4)

**Comment by chenshinshi** [comment]
<img width="421" alt="cdbf469fc706e3b7a6227dd285df2166" src="https://github.com/caohongliang92/siyuan-plugin-more-cover/assets/125173405/18f035dd-77a5-49e2-a41a-de49b9ae9a05">
没适配时夜间死亡配色

**Comment by caohongliang92** [comment]
嗯，确实有问题，有空改改

**Comment by caohongliang92** [comment]
你有思源主题颜色变量的文章嘛，很多变量我都不熟悉

**Comment by chenshinshi** [comment]
你可以看下其他插件做的界面的取色，比如自定義字型的菜單。
